server {
    listen 80;
    server_name evarkadasim.co www.evarkadasim.co;

    root /var/www/evarkadasim;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /_expo/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}

server {
    listen 80;
    server_name api.evarkadasim.co;

    location / {
        proxy_pass http://127.0.0.1:5118;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
